name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-kindlepw2:
    runs-on: ubuntu-latest

    steps:
    - name: Download toolchain
      run: wget -q https://github.com/KindleModding/koxtoolchain/releases/latest/download/kindlepw2.tar.gz -O - | tar -xzf - -C ~
    
    - uses: actions/checkout@v4
      with:
        repository: KindleModding/kindle-sdk
        submodules: recursive
        path: kindle-sdk
    - name: "Setup kindle-sdk"
      run: |
          sudo apt-get install -y zlib1g-dev libarchive-dev nettle-dev curl
          sh ./kindle-sdk/gen-sdk.sh kindlepw2

    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build
      run: |
          sudo apt-get install meson
          meson setup --cross-file ~/x-tools/arm-kindlepw2-linux-gnueabi/meson-crosscompile.txt builddir_kindlepw2
          cd builddir_kindlepw2
          meson compile
    - uses: actions/upload-artifact@v4
      with:
        name: sh_integration-kindlepw2
        path: builddir_kindlepw2

  build-kindlehf:
    runs-on: ubuntu-latest

    steps:
    - name: Download toolchain
      run: wget -q https://github.com/KindleModding/koxtoolchain/releases/latest/download/kindlehf.tar.gz -O - | tar -xzf - -C ~
    
    - uses: actions/checkout@v4
      with:
        repository: KindleModding/kindle-sdk
        submodules: recursive
        path: kindle-sdk
    - name: "Setup kindle-sdk"
      run: |
          sudo apt-get install -y zlib1g-dev libarchive-dev nettle-dev curl
          sh ./kindle-sdk/gen-sdk.sh kindlehf

    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build
      run: |
          sudo apt-get install meson
          meson setup --cross-file ~/x-tools/arm-kindlehf-linux-gnueabihf/meson-crosscompile.txt builddir_kindlehf
          cd builddir_kindlehf
          meson compile
    - uses: actions/upload-artifact@v4
      with:
        name: sh_integration-kindlehf
        path: builddir_kindlehf