name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-kindlehf-toolchain:
    runs-on: ubuntu-latest

    steps:
    - name: Cache X-Tools
      id: cache-x-tools
      uses: actions/cache@v4
      with:
        path: ~/x-tools/
        key: ${{ runner.os }}-x_tools_kindlehf
    - uses: actions/checkout@v4
      if: steps.cache-x-tools.outputs.cache-hit != 'true'
      with:
        repository: NiLuJe/koxtoolchain
    - name: Compile Toolcahin
      if: steps.cache-x-tools.outputs.cache-hit != 'true'
      run: |
          sudo apt-get install build-essential autoconf automake bison flex gawk libtool libtool-bin libncurses-dev curl file git gperf help2man texinfo unzip wget
          ./gen-tc.sh kindlehf
    - uses: actions/upload-artifact@v4
      with:
        name: arm-kindlehf-linux-gnueabihf
        path: ~/x-tools/arm-kindlehf-linux-gnueabihf

  build-kindlepw2-toolchain:
    runs-on: ubuntu-latest

    steps:
    - name: Cache X-Tools
      id: cache-x-tools
      uses: actions/cache@v4
      with:
        path: ~/x-tools/
        key: ${{ runner.os }}-x_tools_kindlepw2
    - uses: actions/checkout@v4
      if: steps.cache-x-tools.outputs.cache-hit != 'true'
      with:
        repository: NiLuJe/koxtoolchain
    - name: Compile Toolcahin
      if: steps.cache-x-tools.outputs.cache-hit != 'true'
      run: |
          sudo apt-get install build-essential autoconf automake bison flex gawk libtool libtool-bin libncurses-dev curl file git gperf help2man texinfo unzip wget
          ./gen-tc.sh kindlepw2
    - uses: actions/upload-artifact@v4
      with:
        name: arm-kindlepw2-linux-gnueabi
        path: ~/x-tools/arm-kindlepw2-linux-gnueabi

  build-kindlepw2:
    runs-on: ubuntu-latest
    needs: [build-kindlepw2-toolchain]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: arm-kindlepw2-linux-gnueabi
        path: ~/x-tools/arm-kindlepw2-linux-gnueabi
    - name: build
      run: |
          sudo apt-get install meson
          ./gen_crosscompile.sh
          meson setup --cross-file kindlepw2.txt builddir_kindlepw2
          cd builddir_kindlepw2
          meson compile
    - uses: actions/upload-artifact@v4
      with:
        name: kindlepw2
        path: builddir_kindlepw2

  build-kindlehf:
    runs-on: ubuntu-latest
    needs: [build-kindlehf-toolchain]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: arm-kindlehf-linux-gnueabihf
        path: ~/x-tools/arm-kindlehf-linux-gnueabihf
    - name: build
      run: |
          sudo apt-get install meson
          ./gen_crosscompile.sh
          meson setup --cross-file kindlehf.txt builddir_kindlehf
          cd builddir_kindlehf
          meson compile
    - uses: actions/upload-artifact@v4
      with:
        name: kindlehf
        path: builddir_kindlehf