name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-kindlepw2:
    runs-on: ubuntu-latest

    steps:
    - name: Download toolchain
      run: wget -q https://github.com/koreader/koxtoolchain/releases/latest/download/kindlepw2.tar.gz -O - | tar -xzf - -C ~
    - name: Export toolchain
      run: echo ~/x-tools/arm-kindlepw2-linux-gnueabi/bin >> $GITHUB_PATH
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/download-artifact@v4
      with:
        name: arm-kindlepw2-linux-gnueabi
        path: ~/x-tools/arm-kindlepw2-linux-gnueabi
    - name: Fix permissions
      run: |
          chown -R $USER: ~/x-tools/
          chmod -R a+rx ~/x-tools/
    - name: build
      run: |
          sudo apt-get install meson
          ./gen_crosscompile.sh
          meson setup --cross-file kindlepw2.txt builddir_kindlepw2
          cd builddir_kindlepw2
          meson compile
    - uses: actions/upload-artifact@v4
      with:
        name: sh_integration-kindlepw2
        path: builddir_kindlepw2

  build-kindlehf:
    runs-on: ubuntu-latest

    steps:
    - name: Download toolchain
      run: wget -q https://github.com/koreader/koxtoolchain/releases/latest/download/kindlehf.tar.gz -O - | tar -xzf - -C ~
    - name: Export toolchain
      run: echo ~/x-tools/arm-kindlehf-linux-gnueabihf/bin >> $GITHUB_PATH
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/download-artifact@v4
      with:
        name: arm-kindlehf-linux-gnueabihf
        path: ~/x-tools/arm-kindlehf-linux-gnueabihf
    - name: Fix permissions
      run: |
          chown -R $USER: ~/x-tools/
          chmod -R a+rx ~/x-tools/
    - name: build
      run: |
          sudo apt-get install meson
          ./gen_crosscompile.sh
          meson setup --cross-file kindlehf.txt builddir_kindlehf
          cd builddir_kindlehf
          meson compile
    - uses: actions/upload-artifact@v4
      with:
        name: sh_integration-kindlehf
        path: builddir_kindlehf